import { LibraryProvider } from "@/contexts/LibrariesProvider";
import { Inter } from "next/font/google";
import { ComponentsLibrary, ThemeLibrary } from './domain.config';
import "./globals.css";
import { logout } from "@/lib/login";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sao Paulo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const styles = ThemeLibrary()
  const { AppBar } = ComponentsLibrary()

  return (
    <html lang="en">
      <body className={inter.className}>
        <LibraryProvider logicApp={'useModified'} styles={styles}>
          <div className={styles.home.main}>
            <AppBar />
            <form
              action={async () => {
                'use server'
                await logout();
              }}>
              <button type='submit'>LogOut</button>
            </form>
            {children}
          </div>
        </LibraryProvider>
      </body>
    </html >
  );
}
