import { LibraryProvider } from "@/contexts/LibrariesProvider";
import { Inter } from "next/font/google";
import { ComponentsLibrary, ThemeLibrary } from './domain.config';
import "./globals.css";
import { StatesProvider } from "@/contexts/StatesContext";
import MainContainer from "@/app/components/MainContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sao Paulo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const styles = ThemeLibrary()
  const { AppBar, NavigationBar } = ComponentsLibrary()

  return (
    <html lang="en">
      <body className={inter.className}>
        <LibraryProvider logicApp={'useModified'} styles={styles}>
          <StatesProvider>
            <div className={styles.home.generalView}>
              <AppBar />
              <div className={styles.home.main}>
                <NavigationBar />
                <MainContainer>
                  {children}
                </MainContainer>
              </div>
            </div>
          </StatesProvider>
        </LibraryProvider>
      </body>
    </html >
  );
}
