import { LibraryProvider } from "@/contexts/LibrariesProvider";
import { Inter } from "next/font/google";
import { ComponentsLibrary, ThemeLibrary } from './domain.config';
import "./globals.css";
import { logout } from "@/lib/login";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sao Paulo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const styles = ThemeLibrary()
  const { AppBar } = ComponentsLibrary()

  return (
    <html lang="en">
      <body className={inter.className}>
        <LibraryProvider logicApp={'useModified'} styles={styles}>
          <div className={styles.home.main}>
            <AppBar />
            <Link className={styles.buttonLink} href="/logout" style={{ color: 'blue' }}>Logout</Link>
            {children}
          </div>
        </LibraryProvider>
      </body>
    </html >
  );
}
