import MainContainer from "@/app/components/MainContainer";
import { Inter } from "next/font/google";
import { ComponentsLibrary } from '../domain.config';
import "./globals.css";
import '@/themes/themeB/themeB.css';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sao Paulo App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const { AppContainer } = ComponentsLibrary()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContainer>
          <div style={{ height: 'calc(100% - 50px)' }}>
            <MainContainer >
              {children}
            </MainContainer>
          </div>
        </AppContainer>
      </body>
    </html >
  );
}
