import { ComponentsLibrary } from '../../domain.config';

const RESPONSE = {
    "apiVersion": "1.0",
    "method": "Book.myBooks",
    "context": "/api/v/1/my/books",
    "params": null,
    "updated": 1713265068,
    "data": {
        "6": {
            "id": 6,
            "isProjectContent": false,
            "name": "oxford_elt_2022 con test generator",
            "description": "",
            "isbn": "525228CD",
            "fullText": "Admin Plataforma oxford_elt_2022 con test generator 525228CD ",
            "units": {
                "13": "Unit 1: Activities (non-gamified)  ",
                "14": "Unit 2: Activities (gamified) ",
                "15": "Unit 3: Prueba slides fase III",
                "17": "Exámenes",
                "18": "Prueba Marielena",
                "93": "Exams"
            },
            "thumb": "/coursePlayer/getimage.php?idcurso=6&t=1712748406",
            "cover": "",
            "author": {
                "id": 1,
                "name": "Admin Plataforma",
                "email": "sadmin@example.org",
                "contributor": "Admin Plataforma"
            },
            "level": 2,
            "subject": 23,
            "online": false,
            "highlighted": false,
            "catalog": true,
            "dateUpdated": 1712748406,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": true,
            "styleCurso": "oxford-elt-2022",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1709718399,
            "lastChanges": 1712748406,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": {
                "unitPlanning": true,
                "activityPlanning": true
            },
            "order": 3,
            "hashCourseIndex": "#activity/4/13/210",
            "isDigitalBook": true,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/librodigital_html.php?idclase=210&idcurso=6",
            "supportTmpuxTOC": false,
            "supportsStyleTextwebOverload": true,
            "customLanguage": "EN",
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": true,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": true,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "idSchoolYears": [
                0
            ],
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": false,
            "canDeallocate": false,
            "canShare": false,
            "shared": false
        },
        "1": {
            "id": 15,
            "isProjectContent": false,
            "name": "Geniox 2022 DEMO",
            "description": "",
            "isbn": "521712RLB",
            "fullText": "Manuel Naranjo Geniox 2022 DEMO 521712RLB ",
            "units": {
                "46": "¿Cómo se usa mi producto?",
                "47": "IMPRESCINDIBLES",
                "48": "Programaciones - lista",
                "49": " Mapa de recursos - cards",
                "50": "Rubricas",
                "51": "Solucionario",
                "52": "Enlaces de interés",
                "53": "Para proyectar",
                "54": "MI LIBRO",
                "55": "U1. El método científico",
                "56": "U1. Tema solo con contenido para el generador",
                "57": "U2. El universo y el sistema solar",
                "58": "U3. La Geosfera ",
                "59": "U4. La atmósfera",
                "60": "U5. La hidrosfera",
                "61": "U6. Los seres vivos: Clasificación y funciones",
                "62": "U7. Los microorganismos y los reinos Moneras, Protoctistas y Fungi",
                "63": "U8. El reino Plantas",
                "64": "E9. El reino Animales. Los invertebrados",
                "65": "E10. El reino Animales. Los vertebrados",
                "66": "E11. La naturaleza es así",
                "67": "E12. Los recursos naturales",
                "68": "E.13. Los volcanes",
                "69": "Adaptación curricular",
                "70": "Evau (mi aprendizaje)",
                "71": "Resúmenes",
                "72": "Exámenes y pruebas PAU",
                "73": "Evalúa",
                "74": "Genera tus exámenes",
                "75": "Mis exámenes",
                "76": "Exámenes Oxford",
                "77": "Exámenes online",
                "78": "Proyectos",
                "79": "Crea un periódico",
                "80": "Experimenta con Kahoot (varios recursos)",
                "81": "Nueva template - Bloque con cuatro rectángulos en linea",
                "82": "Caja 1",
                "83": "Caja 2",
                "84": "Caja 3",
                "85": "Caja 4",
                "86": "Nueva template - Bloque con cinco cuadros",
                "87": "Caja con texto por defecto",
                "88": "Caja  con texto alineado a la izquierda",
                "89": "Caja con texto centrado arriba",
                "90": "Caja con texto en el centro",
                "91": "Caja con texto centrado alineado a la derecha",
                "92": "Exámenes"
            },
            "thumb": "/useruploads/icons/144/190/r/c/15/librochico_429974.png",
            "cover": "/useruploads/r/c/15/zonarecursos.png",
            "author": {
                "id": 7,
                "name": "Manuel Naranjo",
                "email": "profeemail@email.com",
                "contributor": "Editorial Oxford Demo"
            },
            "level": 6,
            "subject": 32,
            "online": true,
            "highlighted": false,
            "catalog": true,
            "dateUpdated": 1712748711,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": true,
            "styleCurso": "oxford_geniox",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1712735089,
            "lastChanges": 1712748711,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": null,
            "order": 2,
            "hashCourseIndex": "#activity/15/46/684",
            "isDigitalBook": false,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/clases2.php?editar=0&idcurso=15&idclase=684&modo=0",
            "supportTmpuxTOC": false,
            "supportsStyleTextwebOverload": true,
            "customLanguage": "ES",
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": false,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": false,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": true,
            "canDeallocate": false,
            "canShare": true,
            "shared": false
        },
        "7": {
            "id": 7,
            "isProjectContent": false,
            "name": "oxford_elt_test_generator (viejo)",
            "description": "",
            "isbn": "525230CD",
            "fullText": "Admin Plataforma oxford_elt_test_generator (viejo) 525230CD ",
            "units": {
                "19": "Unit 3 Human nature",
                "20": "Imprint",
                "21": "Exámenes",
                "24": "Prueba Marielena"
            },
            "thumb": "/coursePlayer/getimage.php?idcurso=7&t=1709718426",
            "cover": "/useruploads/r/c/525191/Key2ED_SB1Cover_page-0001.jpg",
            "author": {
                "id": 1,
                "name": "Admin Plataforma",
                "email": "sadmin@example.org",
                "contributor": "Admin Plataforma"
            },
            "level": 2,
            "subject": 23,
            "online": false,
            "highlighted": false,
            "catalog": true,
            "dateUpdated": 1709718426,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": true,
            "styleCurso": "oxford-elt-test-generator",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1709718426,
            "lastChanges": 1709718426,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": {
                "unitPlanning": true,
                "activityPlanning": true
            },
            "order": 5,
            "hashCourseIndex": "#activity/5/19/326",
            "isDigitalBook": true,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/librodigital_html.php?idclase=326&idcurso=7",
            "supportTmpuxTOC": false,
            "supportsStyleTextwebOverload": true,
            "customLanguage": "EN",
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": true,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": true,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "idSchoolYears": [
                0
            ],
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": false,
            "canDeallocate": false,
            "canShare": false,
            "shared": false
        },
        "8": {
            "id": 8,
            "isProjectContent": false,
            "name": "Contenido ejercicio",
            "description": "",
            "isbn": "",
            "fullText": "Manuel Naranjo Contenido ejercicio  comprension gramática lectura",
            "units": {
                "27": "Tema 1",
                "28": "Actividades copiadas",
                "32": "Exámenes"
            },
            "thumb": "/coursePlayer/getimage.php?idcurso=8&t=1710157749",
            "cover": "",
            "author": {
                "id": 7,
                "name": "Manuel Naranjo",
                "email": "profeemail@email.com",
                "contributor": "Manuel Naranjo"
            },
            "level": 2,
            "subject": 49,
            "online": true,
            "highlighted": true,
            "catalog": true,
            "dateUpdated": 1710157749,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": false,
            "styleCurso": "ocean",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1709718745,
            "lastChanges": 1710157749,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": null,
            "order": 4,
            "hashCourseIndex": "#book/8",
            "isDigitalBook": false,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/curso2.php?idcurso=8",
            "supportTmpuxTOC": true,
            "supportsStyleTextwebOverload": true,
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": false,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": false,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "idSchoolYears": [
                0
            ],
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": false,
            "canDeallocate": false,
            "canShare": true,
            "shared": true
        },
        "10": {
            "id": 10,
            "isProjectContent": false,
            "name": "Competencias",
            "description": "",
            "isbn": "",
            "fullText": "Manuel Naranjo Competencias ",
            "units": {
                "29": "Tema 1",
                "30": "Tema 2",
                "31": "Tema 3"
            },
            "thumb": "/coursePlayer/getimage.php?idcurso=10&t=1712908043",
            "cover": "",
            "author": {
                "id": 7,
                "name": "Manuel Naranjo",
                "email": "profeemail@email.com",
                "contributor": "Manuel Naranjo"
            },
            "level": 2,
            "subject": 49,
            "online": false,
            "highlighted": false,
            "catalog": true,
            "dateUpdated": 1712908043,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": false,
            "styleCurso": "ocean",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1710149875,
            "lastChanges": 1712908043,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": null,
            "order": 0,
            "hashCourseIndex": "#book/10",
            "isDigitalBook": false,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/curso2.php?idcurso=10",
            "supportTmpuxTOC": true,
            "supportsStyleTextwebOverload": true,
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": false,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": false,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "idSchoolYears": [
                0
            ],
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": false,
            "canDeallocate": false,
            "canShare": true,
            "shared": false
        },
        "15": {
            "id": 15,
            "isProjectContent": false,
            "name": "Geniox 2022 DEMO",
            "description": "",
            "isbn": "521712RLB",
            "fullText": "Manuel Naranjo Geniox 2022 DEMO 521712RLB ",
            "units": {
                "46": "¿Cómo se usa mi producto?",
                "47": "IMPRESCINDIBLES",
                "48": "Programaciones - lista",
                "49": " Mapa de recursos - cards",
                "50": "Rubricas",
                "51": "Solucionario",
                "52": "Enlaces de interés",
                "53": "Para proyectar",
                "54": "MI LIBRO",
                "55": "U1. El método científico",
                "56": "U1. Tema solo con contenido para el generador",
                "57": "U2. El universo y el sistema solar",
                "58": "U3. La Geosfera ",
                "59": "U4. La atmósfera",
                "60": "U5. La hidrosfera",
                "61": "U6. Los seres vivos: Clasificación y funciones",
                "62": "U7. Los microorganismos y los reinos Moneras, Protoctistas y Fungi",
                "63": "U8. El reino Plantas",
                "64": "E9. El reino Animales. Los invertebrados",
                "65": "E10. El reino Animales. Los vertebrados",
                "66": "E11. La naturaleza es así",
                "67": "E12. Los recursos naturales",
                "68": "E.13. Los volcanes",
                "69": "Adaptación curricular",
                "70": "Evau (mi aprendizaje)",
                "71": "Resúmenes",
                "72": "Exámenes y pruebas PAU",
                "73": "Evalúa",
                "74": "Genera tus exámenes",
                "75": "Mis exámenes",
                "76": "Exámenes Oxford",
                "77": "Exámenes online",
                "78": "Proyectos",
                "79": "Crea un periódico",
                "80": "Experimenta con Kahoot (varios recursos)",
                "81": "Nueva template - Bloque con cuatro rectángulos en linea",
                "82": "Caja 1",
                "83": "Caja 2",
                "84": "Caja 3",
                "85": "Caja 4",
                "86": "Nueva template - Bloque con cinco cuadros",
                "87": "Caja con texto por defecto",
                "88": "Caja  con texto alineado a la izquierda",
                "89": "Caja con texto centrado arriba",
                "90": "Caja con texto en el centro",
                "91": "Caja con texto centrado alineado a la derecha",
                "92": "Exámenes"
            },
            "thumb": "/useruploads/icons/144/190/r/c/15/librochico_429974.png",
            "cover": "/useruploads/r/c/15/zonarecursos.png",
            "author": {
                "id": 7,
                "name": "Manuel Naranjo",
                "email": "profeemail@email.com",
                "contributor": "Editorial Oxford Demo"
            },
            "level": 6,
            "subject": 32,
            "online": true,
            "highlighted": false,
            "catalog": true,
            "dateUpdated": 1712748711,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": true,
            "styleCurso": "oxford_geniox",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1712735089,
            "lastChanges": 1712748711,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": null,
            "order": 2,
            "hashCourseIndex": "#activity/15/46/684",
            "isDigitalBook": false,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/clases2.php?editar=0&idcurso=15&idclase=684&modo=0",
            "supportTmpuxTOC": false,
            "supportsStyleTextwebOverload": true,
            "customLanguage": "ES",
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": false,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": false,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": true,
            "canDeallocate": false,
            "canShare": true,
            "shared": false
        },
        "16": {
            "id": 16,
            "isProjectContent": false,
            "name": "Oxford Zona Recursos",
            "description": "",
            "isbn": "517222RLB",
            "fullText": "Manuel Naranjo Oxford Zona Recursos 517222RLB ",
            "units": {
                "94": "Antes de empezar",
                "95": "Evalúa",
                "96": "Genera tus exámenes",
                "97": "Mis exámenes",
                "98": "Exámenes Oxford",
                "99": "Ejercicios de verbos",
                "100": "Dictados para la vida vegana",
                "101": "Extraordinaria Tercera Convocatoria",
                "102": "Examen de refuerzo emocional",
                "103": "Examen lorem ipsum",
                "104": "Proyectos",
                "105": "Crea un periódico",
                "106": "Experimenta con Kahoot (varios recursos)",
                "107": "1er Trimestre",
                "108": "Unidad 1",
                "109": "Las modalidades textuales (I)",
                "110": "Tema solo con exámenes",
                "111": "Escritura creativa",
                "112": "Las palabras - EXÁMENES",
                "113": "tema de prueba etiquetas",
                "114": "Experienta con Kahoot",
                "115": "Tema extra exámenes",
                "116": "Unidad 2",
                "117": "Las modalidades textuales ciencias (II)",
                "118": "Interior de la unidad 2 (I)",
                "119": "Interior de la unidad 2 (II)",
                "120": "Ortografía",
                "121": "Tema 3: Varios temas para rellenar la caja y necesitemos scroll (I)",
                "122": "Tema 4: Varios temas para rellenar la caja y necesitemos scroll (I)",
                "123": "Tema 5: Varios temas para rellenar la caja y necesitemos scroll (II)",
                "124": "Tema 6: Varios temas para rellenar la caja y necesitemos scroll (III)",
                "125": "Presentación de la unidad",
                "126": "Presentación de la unidad (II)",
                "127": "Unidad 3",
                "128": "Tema 1: Vamos a incluir un título muy largo para ver como se escribe",
                "129": "Otra caja unidad 3",
                "130": "Y más",
                "131": "Unidad 4",
                "132": "Interior de la unidad 1 trimestre 3",
                "133": "Unidad 5",
                "134": "Unidad 6",
                "135": "2do Trimestre",
                "136": "Unidad 1",
                "137": "Interior de la unidad 1 segundo trimestre (I)",
                "138": "Interior de la unidad 1 segundo trimestre (II)",
                "139": "Unidad 2",
                "140": "Interior de la unidad 2 segundo segundo trimestre",
                "141": "Unidad 3",
                "142": "Unidad 4",
                "143": "Unidad 5",
                "144": "Unidad 6",
                "145": "Caja 1",
                "146": "Caja 2",
                "147": "Caja 3",
                "148": "Caja 4",
                "149": "Caja 5",
                "150": "Caja 6",
                "151": "3er Trimestre",
                "152": "block_template_1_rectangle",
                "153": "Unidad última",
                "154": "block_template_2_rectangle",
                "155": "block_template_3_rectangle",
                "156": "block_template_3_square",
                "157": "block_template_1_square_left_1_right",
                "158": "block_template_1_left_1_square_right",
                "159": "block_template_2_left_1_right",
                "160": "block_template_1_left_2_right",
                "161": "block_template_1_rectangle_left_4_right (plantilla no contemplada)",
                "162": "block_template_1_square_left_4_right",
                "163": "block_template_6_rectangle",
                "164": "block_template_1_left_8_right",
                "165": "block_template_1_left_2_centre_4right",
                "166": "block_template_12_square",
                "167": "Extraordinaria Primera Convocatoria",
                "168": "Extraordinaria Segunda Convocatoria",
                "169": "Exámenes",
                "170": "Caja 1"
            },
            "thumb": "/useruploads/icons/144/190/r/c/16/zonarecursos_617582.png",
            "cover": "/useruploads/r/c/16/zonarecursos_617582.png",
            "author": {
                "id": 7,
                "name": "Manuel Naranjo",
                "email": "profeemail@email.com",
                "contributor": "Editorial Oxford Demo"
            },
            "level": 0,
            "subject": 39,
            "online": true,
            "highlighted": false,
            "catalog": true,
            "dateUpdated": 1712750383,
            "idSchoolYear": 0,
            "previousIdSchoolYear": 0,
            "hasCoverActivity": true,
            "styleCurso": "oxford_zona_recursos_2020",
            "supportsFractionalGrades": false,
            "supportsDownload": true,
            "DownloadInfo": {
                "tipo": "completa"
            },
            "canBeSold": false,
            "isHeavy": false,
            "format": 0,
            "uploadDate": 1712750266,
            "lastChanges": 1712750383,
            "incompatibleDevices": [],
            "urlCompra": "",
            "openInNewTab": false,
            "coursePlanning": null,
            "order": 1,
            "hashCourseIndex": "#activity/16/94/847",
            "isDigitalBook": false,
            "isEpubBook": false,
            "urlAcceso": "/coursePlayer/clases2.php?editar=0&idcurso=16&idclase=847&modo=0",
            "supportTmpuxTOC": false,
            "supportsStyleTextwebOverload": true,
            "hasNoValidCredit": false,
            "activityIndexRequiresCredit": true,
            "requiresCredit": false,
            "isDemo": false,
            "isCustomized": false,
            "isCustomContent": false,
            "isAvailableInBlinkShop": false,
            "requestDemoAvailable": false,
            "isCollaborator": false,
            "canEdit": true,
            "canDelete": true,
            "canDeallocate": false,
            "canShare": true,
            "shared": false
        }
    }
}

export async function ViewBooksSectionSkeleton() {

    return (
        <div>
            <div></div>
            <div></div>
            <ul>
                <li>
                    <div>
                        <div style={{ backgroundImage: `gray` }} >
                        </div>
                    </div>
                    <div></div>
                    <div></div>
                </li>
                <li>
                    <div>
                        <div style={{ backgroundImage: `gray` }} >
                        </div>
                    </div>
                    <div></div>
                    <div></div>
                </li>
                <li>
                    <div>
                        <div style={{ backgroundImage: `gray` }} >
                        </div>
                    </div>
                    <div></div>
                    <div></div>
                </li>
                <li>
                    <div>
                        <div style={{ backgroundImage: `gray` }} >
                        </div>
                    </div>
                    <div></div>
                    <div></div>
                </li>
                <li>
                    <div>
                        <div style={{ backgroundImage: `gray` }} >
                        </div>
                    </div>
                    <div></div>
                    <div></div>
                </li>
            </ul>
        </div >
    )
}

export default async function ViewBooksSection() {

    const fetchData = async () => {
        await new Promise((resolve) => setTimeout(resolve, 3000))
        return RESPONSE
    }

    const response = await fetchData()

    const { ViewBooks } = ComponentsLibrary()

    return (
        <ViewBooks books={response.data} />
    )
}