import { Inter } from "next/font/google";
import { ComponentsLibrary } from '../domain.config';
import "./globals.css";
import '@/themes/themeA/themeA.css';
import MainContainer from "@/app/components/MainContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Blink App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  const { AppContainer } = ComponentsLibrary()

  return (
    <html lang="en">
      <body className={inter.className}>
        <AppContainer>
          <MainContainer >
            {children}
          </MainContainer>
        </AppContainer>
      </body>
    </html >
  );
}
